set_property SRC_FILE_INFO {cfile:/home/tnsai/ws/trojan/AES-trojan/vivado/cw312_a35.xdc rfile:../vivado/cw312_a35.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D15 } [get_ports clk_in]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V10 } [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V11 } [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V14 } [get_ports trig_out]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN R1 } [get_ports led1]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN V2 } [get_ports led2]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN V5 } [get_ports led3]
